[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
decentralized_voting_platform = "6FuguLE3hjvTaexSGjN2GtGPX9jxddvmBXWj5ddBBWqp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
